// <auto-generated />
namespace Task_ListOfEmployees.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migrat94 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrat94));
        
        string IMigrationMetadata.Id
        {
            get { return "201909021518535_migrat94"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
