// <auto-generated />
namespace Task_ListOfEmployees.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migrat93 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrat93));
        
        string IMigrationMetadata.Id
        {
            get { return "201907080947025_migrat93"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
